config/routes.rb
Rails.application.routes.draw do

  resources :projects
  devise_for :admins
  resources :posts
  get 'welcome/index'
  root 'welcome#index'

  get 'tags/:tag', to: 'posts#index', as: :tag
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :content, presence: true
  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings

  def self.tagged_with(name)
    Tag.find_by!(name: name).posts
  end


  def self.tag_counts
    Tag.select("tags.id, tags.name,count(taggings.tag_id) as count").
        joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings
  has_many :posts, through: :taggings

  
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :create, :update, :edit, :destroy]

  def index

    @posts = if params[:tag]
               Post.tagged_with(params[:tag]).order("created_at desc").paginate(:page => params[:page], :per_page => 5)
             else
               Post.all.order("created_at desc").paginate(:page => params[:page], :per_page => 5)
             end
  end

  def show

  end

  def edit

  end

  def update

    if @post.update post_params
      redirect_to @post, notice: "Updated breh"
    else
      render 'edit', notice: "You're fucking up bud"
    end

  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params

    if @post.save
      redirect_to @post, notice: "Nice Job Bro"
    else
      render 'new', notice: "didn't work bud"
    end

  end


  private
  def post_params
    params.require(:post).permit(:title, :content, :tag_list)
  end

  def find_post
    @post = Post.find(params[:id])
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :content, :projecturl)
    end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  layout nil

  def index
    headers['Content-Type'] = 'application/xml'
    last_post = Post.last
    if stale?(:etag => last_post, :last_modified => last_post.updated_at.utc)
      respond_to do |format|
        format.xml {@posts = Post.sitemap} # sitemap is a named scope
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
  end

  def test
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'redcarpet'

  class HTML < Redcarpet::Render::HTML
    def block_code(code ,language)
      print(code)
      CodeRay.scan(code, language).div
    end
  end


  def markdown(content)

    render_options = {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow' }
    }

    extensions = {
      autolink: true,
      fenced_code_blocks: true,
      lax_spacing: true,
      no_intra_emphasis: true,
      strikethrough: true,
    }
    renderer = HTML.new(render_options)  
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(content)
  end

  def tag_cloud(tags, classes)
    max = tags.max_by(&:count)
    tags2 = tags.order('count desc')
    tags2.each do |tag|
      puts tag.name
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html+mobile.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'applicationmobile', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'applicationmobile', 'data-turbolinks-track': 'reload' %>

    <title>Hans Pistor - Website Developer</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <script src="https://use.fontawesome.com/211c51ec0c.js"></script>
    <meta name="viewport" content="width=device-width">

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-100463127-2', 'auto');
        ga('send', 'pageview');

    </script>

  </head>

  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header five">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="name-div">
            <%= link_to "Hans Pistor", root_path, class: "name" %>
          </div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="navbar-paths"><a href="#"><%= link_to "Articles", posts_path %></a></li>
            <li class="navbar-paths"><a href="#"><%= link_to "Projects", projects_path %></a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>

  <body>
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>


  <footer id="main-footer">
    <p class="copyright">&copy;2017 Hans Pistor</p>
    <nav>
      <a href="http://twitter.com/hansthezulu" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
      <a href="https://www.linkedin.com/in/hans-pistor-172914137/" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
      <a href="https://github.com/hanspistorstetson" target="_blank"><i class="fa fa-github" aria-hidden="true"></i></a>
    </nav>
  </footer>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<title>Hans Pistor - Developer</title>
<meta charset="UTF-8">
<%= csrf_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag 'test' %>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Raleway">
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<style>
  body, h1, h2, h3, h4, h5 {
    font-family: "Raleway", sans-serif
  }
</style>

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({tex2jax: {inlineMath:[['$','$']]}});










</script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-111392537-1"></script>
  <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
          dataLayer.push(arguments);
      }

      gtag('js', new Date());

      gtag('config', 'UA-111392537-1');
  </script>

  <meta name="google-site-verification" content="vkIycLFyG9euzcHxRls_WY0VlL7CVgo486NqrADvOaE"/>
  <%= favicon_link_tag 'favicon.ico' %>
</head>

<header>
  <nav class="navbar navbar-default" role="navigation">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle"
              data-toggle="collapse" data-target="#example-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'Hans Pistor', root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-right navbar-collapse" id="example-navbar-collapse">

      <ul class="nav navbar-nav">
        <li><%= link_to 'Posts', posts_path %></li>
        <li><%= link_to 'Projects', projects_path %></li>
        <% if admin_signed_in? %>
          <li><%= link_to "Sign Out", destroy_admin_session_path %></li>
        <% end %>

      </ul>
    </div>

  </nav>
</header>

<body>
<div id="allcontent">
  <%= yield %>
</div>
</body>

<footer class="w3-container w3-dark-grey w3-padding-32 w3-margin-top">

</footer>

<script type="text/javascript">
    if (window.MathJax) {
        MathJax.Hub.Queue(
            ['Typeset', MathJax.Hub]
        );
    }
</script>


</html>

app/views/layouts/backup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Hans Pistor - Website Developer</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <script src="https://use.fontawesome.com/211c51ec0c.js"></script>

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-100463127-2', 'auto');
        ga('send', 'pageview');

    </script>

  </head>

  <header id="main-nav" class="clearfix">
    <%= link_to "Hans Pistor", root_path, class: "name" %>
    <nav>
      <a href="#"><%= link_to "Articles", posts_path %></a>
      <a href="#"><%= link_to "Projects", projects_path %></a>
      <% if admin_signed_in? %>
          <%= link_to "Log Out", destroy_admin_session_path, method: :delete %>
      <% end %>
    </nav>
  </header>

  <body>
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>

  <footer id="main-footer">
    <p class="copyright">&copy;2017 Hans Pistor</p>
    <nav>
      <a href="http://twitter.com/hansthezulu" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
      <a href="https://www.linkedin.com/in/hans-pistor-172914137/" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
      <a href="https://github.com/hanspistorstetson" target="_blank"><i class="fa fa-github" aria-hidden="true"></i></a>
    </nav>
  </footer>


</html>

app/views/posts/_form.html.erb
<div class="new-posts">
  <div class="post-form">
    <%= form_for @post do |f| %>
        <% if @post.errors.any? %>
            <h2><%= pluralize(@post.errors.count, "error") %> prevented this from saving</h2>
            <ul>
              <% @post.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
        <% end %>

        <%= f.label :title %><br>
        <%= f.text_field :title %>

        <br>
        <br>

        <div class="field">
          <%= f.label :tag_list, "Tags (separated by commas)" %><br/>
          <%= f.text_field :tag_list %>
        </div>
        <br>
        <br>

        <%= f.label :content, "Write your article here" %> <br>
        <%= f.text_area :content %>

        <%= f.submit %>


    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="new-posts">
  <h1>Edit Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page-title">
  Blog Posts
</h1>


<div id="post-wrapper" class="skinny-wrapper">
  <div class="post">
    <% if admin_signed_in? %>
        <p class="admin_welcome">Welcome back Hans</p>
        <%= link_to "Add an Article", new_post_path, :class => "btn btn-success" %>
        <hr>
    <% end %>
  </div>

  <div id="tag_cloud">
    <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
    <hr>
  </div>
  <% @posts.each do |post| %>
      <div class="post">
        <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
        <h2><a href="#"><%= link_to post.title, post %></a></h2>
        <p>
          <%= raw post.tags.map(&:name).map {|t| link_to t, tag_path(t)}.join(', ') %>
        </p>
        <hr>
      </div>
  <% end %>

  <div class="post">
    <%= will_paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<h1 class="center">Create A Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post-show-content" class="skinny-wrapper wrapper_padding">
  <header>
    <div class="admin-show">
      <% if admin_signed_in? %>
          <p class="admin_welcome">Your greatest creation Hans</p>
          <%= link_to "Edit this Article", edit_post_path(@post), :class => "btn btn-warning" %>
          <%= link_to "Delete this Article", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger" %>
          <hr>
      <% end %>
    </div>
    <p class="date"><%= @post.created_at.strftime("%A, %b %d") %></p>
    <h1 class="posttitle""><%= @post.title %></h1>
    <hr>
  </header>

  <div id="content">
    <p><%= raw markdown @post.content %></p>
  </div>
  <hr>
  <div id="share_box">
    <p>Share <%= @post.title %></p>

    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
  </div>
</div>

app/views/projects/_form.html.erb
<div class="new-posts">
  <div class="post-form">
    <%= form_with(model: project, local: true) do |form| %>
        <% if project.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

              <ul>
                <% project.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, id: :project_name %>
        </div>

        <div class="field">
          <%= form.label :content %>
          <%= form.text_area :content, id: :project_content %>
        </div>

        <div class="field">
          <%= form.label :projecturl %>
          <%= form.text_field :projecturl, id: :project_projecturl %>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1 id="page-title">
  Projects
</h1>

<div id="post-wrapper" class="skinny-wrapper">
  <div class="post">
    <% if admin_signed_in? %>
        <p class="admin_welcome">Welcome back Hans</p>
        <%= link_to "Add a Project", new_project_path, :class => "btn btn-success" %>
        <hr>
    <% end %>
  </div>
</div>

<div id="project-wrapper" class="skinny-wrapper">
  <% @projects.each do |project| %>
      <div class="project">
        <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
        <h2><a href="#"><%= link_to project.name, project %></a></h2>
      </div>
  <% end %>

  <div class="clearfix"></div>
</div>

<!--
<tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.content %></td>
        <td><%= project.projecturl %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>
-->

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div id="post-show-content" class="skinny-wrapper wrapper_padding">
  <header>
    <div class="admin-show">
      <% if admin_signed_in? %>
          <p class="admin_welcome">Your greatest creation Hans</p>
          <%= link_to "Edit this Project", edit_project_path(@project), :class => "btn btn-warning" %>
          <%= link_to "Delete this Project", project_path(@project), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger" %>
          <hr>
      <% end %>
    </div>
    <p class="date"><%= @project.created_at.strftime("%A, %b %d") %></p>
    <h1><%= @project.name %></h1>
    <hr>
  </header>

  <div id="content">
    <p><%= raw markdown @project.content %></p>
  </div>
  <hr>
  <div id="share_box">
    <p>Share <%= @project.name %></p>

    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
  </div>
</div>

app/views/sitemap/index.html.erb
<h1>Sitemap#index</h1>
<p>Find me in app/views/sitemap/index.html.erb</p>

app/views/welcome/articles.html.erb
<!DOCTYPE html>

<html>

  <head>
    <title>Hans Pistor - Website Developer</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <script src="https://use.fontawesome.com/211c51ec0c.js"></script>
  <body>
    <header id="main-nav" class="clearfix">
      <a href="#" class="name">Hans Pistor</a>
      <nav>
        <a href="articles.html.erb">Articles</a>
        <a href="#">Projects</a>
        <a href="#">Contact</a>
      </nav>
    </header>

    <h1 id="page-title">
      Blog Posts
    </h1>

    <div id="post-wrapper" class="skinny-wrapper">
      <div class="post">
        <p class="date">Monday June 5th</p>
        <h2><a href="#">Why are you using Blogger??</a></h2>
        <hr>
      </div>

      <div class="post">
        <p class="date">Monday June 5th</p>
        <h2><a href="#">Why are you using Blogger??</a></h2>
        <hr>
      </div>

      <div class="post">
        <p class="date">Monday June 5th</p>
        <h2><a href="#">Why are you using Blogger??</a></h2>
        <hr>
      </div>

    </div>

    <div class="clearfix test2">
      <p>whats happening here</p>
    </div>

    <div class="testdiv">
      <p>What in the world is happening</p>
    </div>


    <footer id="main-footer">
      <p class="copyright">&copy;2017 Hans Pistor</p>
      <nav>
        <a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>
        <a href=""><i class="fa fa-linkedin" aria-hidden="true"></i></a>
        <a href=""><i class="fa fa-github" aria-hidden="true"></i></a>
      </nav>
    </footer>

  </body>

</html>

app/views/welcome/index.html.erb
<!-- w3-content defines a container for fixed size centered content,
and is wrapped around the whole page content, except for the footer in this example -->
<div class="content" style="max-width:1400px">


  <!-- Grid -->
  <div class="row">

    <div class="about col-md-4">

      <h2>About</h2>
      <hr class="stylediv">
      <p><%= link_to image_tag("me.png", class: "portrait") %></p>
      <p>I'm a website and software developer living in
        Florida.</p>
      <p>
        I attend Stetson University for Computer Science. I'm a
        member of many clubs including the Sigma Nu Fraternity
        and Stetson Kiwanis Club.
      </p>
      <p>
        Find me complaining on my lack
        of creativity on any social media platform, mainly
        Reddit and Twitter
      </p>

    </div>
    <hr class="mobilediv center-block">
    <div class="posts col-md-4 center-block">
      <h2>Blog Posts</h2>
      <hr class="stylediv center-block">
      <% @posts.each do |post| %>

          <h3><a href="#"><%= link_to post.title, post, class: "post" %></a></h3>
          <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
      <% end %>
    </div>
    <hr class="mobilediv">
    <div class="projects col-md-4 center-block">
      <h2>Projects</h2>
      <hr class="stylediv center-block">
      <% @projects.each do |project| %>
          <h3><a href="#"><%= link_to project.name, project, class: "project" %></a></h3>
          <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
      <% end %>
    </div>
    <hr class="mobilediv">


  </div>
  <br>

  <!-- END w3-content -->
</div>

<!-- Footer -->

app/views/welcome/letsencrypt.html.erb
FdXUxLZdge2iClkDamrPWaH-XbdaTKPPE7gbGfuYzAE.kJWS4XEFw6ycpWSA5mQitaZWN_K5cSUeYyolceKs7RA